When you run an operation in TensorFlow, you need to do it in the context of a <b>Session</b>
<li>A session <font color="blue">holds the computation graph</font>, which contains the tensors and the operations</li>

1. tf.constant->Creates a constant of the necessary <font color="blue">shape</font> and applies the constant operator to it to fill it with the provided values

2. tf.add->Just <font color="blue">puts the add to the computation graph</font>. It <font color="red">DOES NOT evaluate yet</font>

3. output.eval(): Runs the computational graph

In [2]:
from __future__ import print_function

import tensorflow as tf

with tf.Session():
    input1 = tf.constant([1.0, 1.0, 1.0, 1.0])
    input2 = tf.constant([2.0, 2.0, 2.0, 2.0])
    output = tf.add(input1, input2)
    result = output.eval()
    print("result: ", result)

result:  [3. 3. 3. 3.]


<h1>Multiply Vectors</h1> 

<li>We are taking a 1 x 4 vector [1 0 0 1] and multiplying it by a <b>4 by 2</b> </li>
<li>4 by 2 matrix is full of random values from a normal distribution (mean 0, stdev 1)</li>

<h1>This is the BASIS of a NEURAL NETWORK</h1> 
<li>If we are reading in the input features, along with some expected output, and <font color="blue">change the weights based on the error with the output each time</font>, thats a neural network</li>



In [3]:
#@test {"output": "ignore"}
import tensorflow as tf
import numpy as np

with tf.Session():
    input_features = tf.constant(np.reshape([1, 0, 0, 1], (1, 4)).astype(np.float32))
    weights = tf.constant(np.random.randn(4, 2).astype(np.float32))
    output = tf.matmul(input_features, weights)
    print("Input:")
    print(input_features.eval())
    print("Weights:")
    print(weights.eval())
    print("Output:")
    print(output.eval())

Input:
[[1. 0. 0. 1.]]
Weights:
[[ 0.41224805 -0.86906415]
 [-1.020707   -0.03951629]
 [ 1.2193007   0.13509345]
 [-0.45341712  1.1272421 ]]
Output:
[[-0.04116908  0.25817794]]
