<h1>Addition of Vectors</h1>

When you run an operation in TensorFlow, you need to do it in the context of a <b>Session</b>
<li>A session <font color="blue">holds the computation graph</font>, which <font color="blue">contains the tensors</font> and the operations</li>

1. tf.constant->Creates a constant of the necessary <font color="blue">shape</font> and applies the constant operator to it to fill it with the provided values

2. tf.add->Just <font color="blue">puts the add to the computation graph</font>. It <font color="red">DOES NOT evaluate yet</font>

3. <font color="red">output.eval()</font>: <b>Runs</b> the computational graph

In [4]:
from __future__ import print_function

import tensorflow as tf

# We need a session to interact with Tensor flow
with tf.Session():
    input1 = tf.constant([1.0, 1.0, 1.0, 1.0])
    input2 = tf.constant([2.0, 2.0, 2.0, 2.0])
    # tf.add is just an indication of addition. It does not add yet. We have to call .eval()
    output = tf.add(input1, input2)
    result = output.eval()
    print("result: ", result)

result:  [3. 3. 3. 3.]


In [7]:
#@test {"output": "ignore"}
import tensorflow as tf
import numpy as np
with tf.Session():
    # we can input data from numpy as we well. This is an alternate for tf.constant
    # np.reshape just gives a new shape for an array, viz, [1, 0, 0, 1]. 
    #  (1,4) is the new shape meaning 1x4 [int or tuple]. See example named arrays under numpy_basics
    #   astype converts one format to another. Here it converts to float32
    input_features = tf.constant(np.reshape([1, 0, 0, 1], (1, 4)).astype(np.float32))
    # This produces output as [[1. 0. 0. 1.]]. meaning 1 is converting to 1.
    
    # np.random produces random number
    weights = tf.constant(np.random.randn(4, 2).astype(np.float32))
    # weights is of matrix size 4x2. When multiplied with input, it will provide 1x2 matrix
    
    # tf.matmul is a MATRIX Multiplication
    output = tf.matmul(input_features, weights)
    print("Input:")
    print(input_features.eval())
    print("Weights:")
    print(weights.eval())
    print("Output:")
    # weights is of matrix size 4x2. When multiplied with input, it will provide 1x2 matrix
    print(output.eval())

Input:
[[1. 0. 0. 1.]]
Weights:
[[-0.16602631 -0.08566899]
 [ 0.69437003 -0.3418643 ]
 [-0.6089403   1.8519589 ]
 [ 0.56552786 -0.28416568]]
Output:
[[ 0.39950156 -0.36983466]]
